name: Cypress Tests

on:
  push:
    branches:
      - main # Change this to your main branch name
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19 # Choose your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build and Start Server
        run: |
          npm run build
          npm run start &
        # '&' runs the command in the background, releasing control to the next step immediately

      - name: Run Cypress Tests
        run: npm run cy:run
